name: Pull Request

on:
  pull_request:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}  # デプロイしないため PR レベルの排他制御
  cancel-in-progress: true # PR の更新があった場合は前のジョブをキャンセルする

permissions: {}

jobs:
  status-check:
    needs:
      - document-test
      - update-aqua-checksums
      - web-deploy-staging
      - terraform-plan
    runs-on: ubuntu-latest
    permissions: {}

    if: failure()
    steps:
      - run: exit 1

  document-test:
    uses: ./.github/workflows/wc-document-pull-request.yaml
    secrets:
      APP_ID: ${{secrets.APP_ID}}
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
    permissions:
      id-token: write
      contents: read
      pull-requests: write

  update-aqua-checksums:
    uses: ./.github/workflows/wc-update-aqua-checksums.yaml
    secrets:
      APP_ID: ${{secrets.APP_ID}}
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
    permissions:
      id-token: write
      contents: read
      pull-requests: write

  web-deploy-staging:
    environment: staging
    uses: ./.github/workflows/wc-web-deploy-staging.yaml
    with:
      BASE_URL: ${{vars.BASE_URL}}
      S3_URL: ${{vars.S3_URL}}
      DISTRIBUTION_ID: ${{vars.DISTRIBUTION_ID}}
    secrets:
      APP_ID: ${{secrets.APP_ID}}
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      CLOUDFLARE_ZONE_ID: ${{secrets.CLOUDFLARE_ZONE_ID}}
      CLOUDFLARE_CACHE_PURGE_API_TOKEN: ${{secrets.CLOUDFLARE_CACHE_PURGE_API_TOKEN}}
    permissions:
      id-token: write
      contents: read
      pull-requests: write

  terraform-plan:
    environment: staging
    uses: ./.github/workflows/wc-terraform-pull-request.yaml
    secrets:
      APP_ID: ${{secrets.APP_ID}}
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      CLOUDFLARE_READ_ONLY_API_TOKEN: ${{secrets.CLOUDFLARE_READ_ONLY_API_TOKEN}}
      CLOUDFLARE_WRITABLE_API_TOKEN: ${{secrets.CLOUDFLARE_WRITABLE_API_TOKEN}}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
