name: Web Deploy Production

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/pull-request.yaml
      - .github/workflows/web**
      - .github/workflows/wc-web**
      - web/**
      - aqua.yaml

concurrency:
  group: web-production # デプロイ先が1つしかないため repo 内で排他制御
  cancel-in-progress: false

jobs:
  check-need-deploy:
    environment: production

    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      paths: ${{ steps.filter.outputs.paths }}
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Filter paths
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          # 変更したファイルがいずれかにマッチすれば true
          filters: |
            paths:
              - 'web/**'

  web-build-and-deploy-production:
    needs:
      - check-need-deploy

    environment:
      name: production
      url: ${{ vars.BASE_URL }}

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      actions: read # artifact を取得するために必要
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.60.1
        env:
          AQUA_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3.2.1
        with:
          hugo-version: '0.123.7'

      - name: Build
        working-directory: web
        run: github-comment exec -k common -var env:Production -var title:"Build" -- hugo --minify
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        if: needs.check-need-deploy.outputs.paths == 'true'
        with:
          role-to-assume: arn:aws:iam::158677943024:role/github_cube-unit.net_web_deploy_production
          aws-region: ap-northeast-1

      - name: Deploy
        if: needs.check-need-deploy.outputs.paths == 'true'
        working-directory: web
        run: github-comment exec -k deploy-to-s3 -var env:Production -- aws s3 sync --delete public ${{ vars.S3_URL }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Purge Cache - Cloudfront
        if: needs.check-need-deploy.outputs.paths == 'true'
        run: aws cloudfront create-invalidation --distribution-id ${{vars.DISTRIBUTION_ID}} --paths "/*"

      - name: Purge Cache - Cloudflare
        if: needs.check-need-deploy.outputs.paths == 'true'
        uses: jakejarvis/cloudflare-purge-action@eee6dba0236093358f25bb1581bd615dc8b3d8e3 # v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_CACHE_PURGE_API_TOKEN }}
          PURGE_URLS: '["${{ vars.BASE_URL }}", "${{ vars.BASE_URL }}/"]'

  success:
    needs: web-build-and-deploy-production

    environment: production

    if: ${{ !failure() }}

    runs-on: ubuntu-latest

    steps:
      - run: echo "Success!!"
