name: web-deploy-staging

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/web**
      - web/**

concurrency:
  group: web-staging # デプロイ先が1つしかないため repo 内で排他制御
  cancel-in-progress: true

jobs:
  check-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.53.7

      - id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - run: github-comment exec -- github-comment hide
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli2

      - name: Lint Markdown Files
        run: github-comment exec -k common-error -var env:Staging -var title:"Check Markdown Failed" -- markdownlint-cli2 "**/*.md" --config ".markdownlint.json"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  deploy-staging:
    needs: check-documentation
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.53.8

      - id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: '0.123.7'

      - name: Build
        working-directory: web
        run: github-comment exec -k common-error -var env:Staging -var title:"Build Failed" -- hugo
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::158677943024:role/github_cube-unit.net_web_deploy_staging
          aws-region: ap-northeast-1

      - name: Purge Cache
        run: aws cloudfront create-invalidation --distribution-id E27GH5YU41F43Y --paths "/*"

      - name: Deploy
        working-directory: web
        run: github-comment exec -k deploy-to-s3 -var env:Staging -- aws s3 sync --delete public s3://stg.cube-unit.net
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
